use_default_settings: true

server:
  secret_key: "daily-stock-analysis-searxng"
  bind_address: "0.0.0.0"
  public_instance: false

search:
  formats:
    - html
    - json

engines:
  - name: chinaso news
    engine: chinaso
    shortcut: chinaso
    categories:
      - general
      - news
    chinaso_news_source: all
    inactive: false
